# Generated by Django 3.1.7 on 2021-03-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nothotdog', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imageLocation',
            new_name='image_location',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
