# Generated by Django 3.1.7 on 2021-03-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nothotdog', '0004_auto_20210303_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_location',
            new_name='image',
        ),
    ]
