# Generated by Django 3.1.7 on 2021-03-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nothotdog', '0005_auto_20210303_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='valid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
